version: '3.4'

services:
  postgres:
    image: postgres:14.7-alpine
    build: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5432:5432
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    command: sh -c 'php artisan serve --host=0.0.0.0 --port=8000'
    links: 
      - postgres
    depends_on:
      - postgres
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    command: sh -c 'npm run watch'
    links: 
      - backend
    depends_on:
      - backend